# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: apeis-dev

    steps:
    - uses: actions/checkout@v3
    - name: Set up PowerShell
      uses: microsoft/setup-powershell@v1
      with:
          pwsh-version: '7.2'
          modules: '@{module="WebAdministration"; required=$true}'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal  
    - name: Stop IIS
      shell: pwsh
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name 'APEIS'
        Stop-Website -Name 'APEIS'
    - name: Start IIS
      shell: pwsh
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name 'APEIS'
        Start-Website -Name 'APEIS'

#     - name: Deploy to IIS
#       run: |
#        echo "iis stopping"
#        stop-webapppool {iis apppool APEIS}
#       # stop-iissite -Name {iis website APEIS} -Confirm: $false
#       # echo "copy started"
#       # Copy-Item ./apeis/apeis/apeis/* C:/inetpub/wwwroot/APEIS -Recurse -Force -Recurse -Force
#       # echo "copy complete"
#       # start-webapppool {iis apppool APEIS}
#       # start-iissite {iis website APEIS}
#       # echo "iis restarted"
